baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'stack'

[pagination]
  pagerSize = 10

[params]
  mainSections = ["posts"]

name = "Stack"
license = "GPL-3.0-only"
licenselink = "https://github.com/CaiJimmy/hugo-theme-stack/blob/master/LICENSE"
description = "Card-style Hugo theme designed for bloggers"
homepage = "https://github.com/CaiJimmy/hugo-theme-stack"
demosite = "https://demo.stack.jimmycai.com"

tags = ["blog", "responsive", "clean", "light", "dark", "personal"]

features = [
    "disqus",
    "photoswipe",
    "opengraph",
    "widgets",
    "darkmode",
    "table of contents",
    "search",
]

min_version = "0.123.0"

[author]
name = "Jimmy"
homepage = "https://jimmycai.com"

[params.comments]
enabled = true
provider = "giscus"

[params.comments.giscus]
repo = "rich0022/myblog"
repoId = "R_kgDOO2aRnw"
category = "Blog Comments"
categoryId = "DIC_kwDOO2aRn84CrEMy"
mapping = "pathname"
strict = false
reactionsEnabled = "1"
emitMetadata = "1"
inputPosition = "top"
theme = "preferred_color_scheme"
lang = "zh-CN"
loading = "lazy"